### ISSUE TITLE
spanner: unconsumed/uniterated StreamedResultSet doesn't send request to Cloud Spanner server

### ISSUE THREAD

**Issue by odeke-em** [googleapis/python-spanner#17] opened 2020-02-18 00:58 UTC
This is an issue that has plagued me for a while but I just got the time to make a repro.

Basically, if I try for example to invoke Transaction.execute_sql and do NOT consume the result e.g.
```python
txn.execute_sql('DELETE from T1 WHERE 1=1')
```
instead of
```python
res = txn.execute_sql('DELETE from T1 WHERE 1=1')
_ = list(res)
```
then the table will NOT be purged.

Seems like a bug to me with the underlying gRPC library, but it would be useful to explicitly document/call-out this bug if we don't have the bandwidth to fix it, to avoid unexpected problems for customers. It definitely sunk some hours for me in the past and also just right now.

**Comment by larkee** [comment] 2020-02-27 00:22
I am struggling to reproduce this.

Code:
```
from google.cloud.spanner import Client, BurstyPool
from google.cloud.spanner_v1.pool import SessionCheckout

client = Client()
instance = client.instance(INSTANCE)

pool = BurstyPool()
db = instance.database(DATABASE, pool=pool)

with db.snapshot() as snapshot:
    results = snapshot.execute_sql(
        'SELECT VenueId FROM Venues')
    for row in results:
        print(u'VenueId: {}'.format(*row))

with SessionCheckout(pool) as sess:
    txn = sess.transaction()
    txn.begin()

    txn.execute_update('DELETE from Venues WHERE 1=1')
    print("table deleted")

    txn.commit()

with db.snapshot() as snapshot:
    results = snapshot.execute_sql(
        'SELECT VenueId FROM Venues')
    for row in results:
        print(u'VenueId: {}'.format(*row))
```

Output:
```
VenueId: 4
VenueId: 19
VenueId: 42
table deleted
```

The table is not deleted until the transaction is committed. Could you confirm that you are committing the transaction and still experiencing this bug?

**Comment by odeke-em** [comment] 2020-03-03 06:34
Thank you for the response @larkee!

Here is a fully running example that will trigger the issue with an emphasis here
```python
    # 2. Populate the table.
    with SessionCheckout(pool) as sess:
        with sess.transaction() as txn:
            # Transaction.insert unfortunately batches results until .commit() is 
            # invoked so we'll just use execute_sql
            for venue in venues:
                id, name = venue
                res = txn.execute_sql('INSERT INTO Venue(id, name) VALUES (@id, @name)',
                        params={'id': id, 'name': name},
                        param_types={
                            'id': param_types.STRING,
                            'name': param_types.STRING,
                        })

                if False:  # Set this to True so that the library will send the request.
                    _ = list(res)
```

and the full code snippet below:
```python
from google.cloud.spanner import Client, BurstyPool
from google.cloud.spanner_v1.pool import SessionCheckout
from google.cloud.spanner_v1 import param_types

def tables_in_db(db):
    with db.snapshot() as snapshot:
        listing = list(snapshot.execute_sql('''
            SELECT
              t.table_name
            FROM
              information_schema.tables AS t
            WHERE
              t.table_catalog = '' and t.table_schema = ''
            '''))

        return {key[0]: True for key in listing}

def main():
    instance = Client().instance('django-tests')

    pool = BurstyPool()
    db = instance.database('issues-17', pool=pool)
    if not db.exists():
        db.create()

    tables = tables_in_db(db)
    venue_exists = tables.get('Venue', None)

    if not venue_exists:
        # 1. Create the table.
        _ = db.update_ddl([
        '''CREATE TABLE Venue (
            id STRING(MAX) NOT NULL,
            name STRING(MAX)
        ) PRIMARY KEY (id)'''
        ]).result()
    else:
        # 1. Clear out the table.
        with SessionCheckout(pool) as sess:
            with sess.transaction() as txn:
                res = txn.execute_update('DELETE from Venue WHERE 1=1')
                # Explicitly consume the result since here we want to
                # clean and setup the table, in order to reproduce the bug.
                _ = res

    venues = [
        ('0e39782a-7a45-4144-a70d-2b7c2f7130cd', 'Nairobi'),
        ('7b04a798-74e6-4162-946b-910a3536336e', 'Casablanca'),
        ('945ed3d3-915f-4824-9097-041c054b2b29', 'San Diego'),
        ('f0c0367e-692d-456d-9f9c-3e5d3388f86a', 'Melbourne'),
    ]

    # 2. Populate the table.
    with SessionCheckout(pool) as sess:
        with sess.transaction() as txn:
            # Transaction.insert unfortunately batches results until .commit() is 
            # invoked so we'll just use execute_sql
            for venue in venues:
                id, name = venue
                res = txn.execute_sql('INSERT INTO Venue(id, name) VALUES (@id, @name)',
                        params={'id': id, 'name': name},
                        param_types={
                            'id': param_types.STRING,
                            'name': param_types.STRING,
                        })

                if False:  # Set this to True so that the library will send the request.
                    _ = list(res)

            # Now list them out.
            got_l = list(txn.execute_sql('SELECT * from Venue'))
            got = set(tuple(row) for row in got_l)
            want = set(venues)
            if got != want:
                print('Mismatch between Venues after insertion\nGot:  %s\nWant: %s' % (got, want))

if __name__ == '__main__':
    main()
```

### When not iterating over the StreamedResultSet
```shell
GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/appdev-soda-spanner-staging-b842e628aa41-orijtech.json python3 main.py 
Mismatch between Venues after insertion
Got:  set()
Want: {('f0c0367e-692d-456d-9f9c-3e5d3388f86a', 'Melbourne'), ('0e39782a-7a45-4144-a70d-2b7c2f7130cd', 'Nairobi'), ('945ed3d3-915f-4824-9097-041c054b2b29', 'San Diego'), ('7b04a798-74e6-4162-946b-910a3536336e', 'Casablanca')
```

### When iterating over the StreamedResultSet
```diff
--- main.py	2020-03-02 22:32:23.000000000 -0800
+++ main.py	2020-03-02 22:31:38.000000000 -0800
@@ -64,7 +64,7 @@
                             'name': param_types.STRING,
                         })
 
-                if True:  # Set this to True so that the library will send the request.
+                if False:  # Set this to True so that the library will send the request.
                     _ = list(res)
 
             # Now list them out.
```
produces
```shell
GOOGLE_APPLICATION_CREDENTIALS=~/Downloads/appdev-soda-spanner-staging-b842e628aa41-orijtech.json python3 main.py 
```
it passes.

As you can the only change there was invoking `_ = list(res)` after the transaction.execute, and regardless of whether I commit or not, the problem occurs within the Transaction.

**Comment by larkee** [comment] 2020-03-04 05:44
Ahhhh. I have managed to reproduce the problem and figured out the cause!

`txn.execute_sql` returns a generator which means the statement is not executed until you use the iterator. I believe the reason for this is that `execute_sql` is intended to be used for read-only statements in which you would iterate over the results.

However `txn.execute_update` executes the statement and returns the number of rows that were affected. This means you can use this without checking the result and it will work as intended. 

Example:
```
from google.cloud.spanner import Client, BurstyPool
from google.cloud.spanner_v1.pool import SessionCheckout
from google.cloud.spanner_v1 import param_types

client = Client()
instance = client.instance(INSTANCE)

pool = BurstyPool()
db = instance.database(DATABASE, pool=pool)

with db.snapshot() as snapshot:
    results = snapshot.execute_sql('SELECT SingerId FROM Singers')
    for row in results:
        print(u'SingerId: {}'.format(*row))

with SessionCheckout(pool) as sess:
    with sess.transaction() as txn:
        txn.execute_update('DELETE from Singers WHERE 1=1')
        print("deleted")

        for i in range(0,10):
            txn.execute_update('INSERT INTO Singers(SingerId) VALUES (@id)',
                params={'id': i},
                param_types={'id': param_types.INT64}
            )
        print("inserted")

        results = txn.execute_sql('SELECT SingerId FROM Singers')
        for row in results:
            print(u'SingerId: {}'.format(*row))
print("committed")

with db.snapshot() as snapshot:
    results = snapshot.execute_sql('SELECT SingerId FROM Singers')
    for row in results:
        print(u'SingerId: {}'.format(*row))
``` 
Output:
```
deleted
inserted
SingerId: 0
SingerId: 1
SingerId: 2
SingerId: 3
SingerId: 4
SingerId: 5
SingerId: 6
SingerId: 7
SingerId: 8
SingerId: 9
commited
SingerId: 0
SingerId: 1
SingerId: 2
SingerId: 3
SingerId: 4
SingerId: 5
SingerId: 6
SingerId: 7
SingerId: 8
SingerId: 9
```

I will add an issue to improve the documentation to make the distinction that `execute_sql` is intended to be read-only.

**Closed** 2020-03-24 04:03 UTC
Labels: api: spanner, priority: p2, type: docs
