### ISSUE TITLE
Test failures: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by major** [googleapis/python-spanner#728] opened 2022-05-09 20:55 UTC
#### Environment details

  - OS type and version: Fedora 35 (Linux)
  - Python version: `Python 3.10.2`
  - pip version: `pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)`
  - `google-cloud-spanner` version: `3.14.0`

#### Steps to reproduce

  1. Build the Fedora python-google-cloud-spanner package with tests enabled
  2. Tests fail with the following message:

#### Stack trace

Most test failures have the same last line shown here:

```
________ ERROR collecting tests/unit/spanner_dbapi/test_parse_utils.py _________
tests/unit/spanner_dbapi/test_parse_utils.py:18: in <module>
    from google.cloud.spanner_v1 import param_types
../../BUILDROOT/python-google-cloud-spanner-3.14.0-1.fc35.x86_64/usr/lib/python3.10/site-packages/google/cloud/spanner_v1/__init__.py:64: in <module>
    from google.cloud.spanner_v1.client import Client
../../BUILDROOT/python-google-cloud-spanner-3.14.0-1.fc35.x86_64/usr/lib/python3.10/site-packages/google/cloud/spanner_v1/client.py:36: in <module>
    from google.cloud.spanner_admin_database_v1 import DatabaseAdminClient
../../BUILDROOT/python-google-cloud-spanner-3.14.0-1.fc35.x86_64/usr/lib/python3.10/site-packages/google/cloud/spanner_admin_database_v1/__init__.py:17: in <module>
    from .services.database_admin import DatabaseAdminClient
../../BUILDROOT/python-google-cloud-spanner-3.14.0-1.fc35.x86_64/usr/lib/python3.10/site-packages/google/cloud/spanner_admin_database_v1/services/database_admin/__init__.py:16: in <module>
    from .client import DatabaseAdminClient
../../BUILDROOT/python-google-cloud-spanner-3.14.0-1.fc35.x86_64/usr/lib/python3.10/site-packages/google/cloud/spanner_admin_database_v1/services/database_admin/client.py:44: in <module>
    from google.iam.v1 import iam_policy_pb2  # type: ignore
/usr/lib/python3.10/site-packages/google/iam/v1/iam_policy_pb2.py:35: in <module>
    from google.iam.v1 import options_pb2 as google_dot_iam_dot_v1_dot_options__pb2
/usr/lib/python3.10/site-packages/google/iam/v1/options_pb2.py:36: in <module>
    _GETPOLICYOPTIONS = DESCRIPTOR.message_types_by_name["GetPolicyOptions"]
E   AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

Several of these tests fail:

```
=========================== short test summary info ============================
ERROR tests/unit/test__opentelemetry_tracing.py - AttributeError: 'NoneType' ...
ERROR tests/unit/test_batch.py - AttributeError: 'NoneType' object has no att...
ERROR tests/unit/test_database.py - AttributeError: 'NoneType' object has no ...
ERROR tests/unit/test_session.py - AttributeError: 'NoneType' object has no a...
ERROR tests/unit/test_snapshot.py - AttributeError: 'NoneType' object has no ...
ERROR tests/unit/test_transaction.py - AttributeError: 'NoneType' object has ...
ERROR tests/unit/gapic/spanner_admin_database_v1/test_database_admin.py - Att...
ERROR tests/unit/gapic/spanner_admin_instance_v1/test_instance_admin.py - Att...
ERROR tests/unit/spanner_dbapi/test_parse_utils.py - AttributeError: 'NoneTyp...
!!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!!
======================== 19 warnings, 9 errors in 1.65s ========================
```

**Comment by major** [comment] 2022-05-09 20:56
Here's a full build log from Fedora's build system: https://kojipkgs.fedoraproject.org//work/tasks/8122/86848122/build.log

**Comment by ansh0l** [comment] 2022-07-07 06:38
Hi @major, we are looking at this issue, but we're not able to replicate the error.

The previous [`build.log`](https://kojipkgs.fedoraproject.org//work/tasks/8122/86848122/build.log) seem to have been rotated. 

On going through the general task logs for task 8122 above at https://kojipkgs.fedoraproject.org/work/tasks/8122/

When parsing the latest `build.log` over the last 2-3 days, we are not seeing the specific error you are mentioning.
Example: https://kojipkgs.fedoraproject.org/work/tasks/8122/89088122/build.log for 04-July, https://kojipkgs.fedoraproject.org/work/tasks/8122/89138122/build.log for 06-July.

Could you please 
1. Let us know if the issue is still happening?
1.1. If yes, then point us to the relevant logs.
1.2 If not, it would be good to know what fixed the error.

**Comment by ansh0l** [comment] 2022-07-07 19:21
Thanks For the information @major , closing the ticket for now. Do let us know in case the issue recurs.

**Closed** 2022-07-07 19:22 UTC
Labels: api: spanner, priority: p2
